Repository Yashshukla11/ExamTime_android, pull requests merged in 2024-05, with the labels that each got.

#42 Jump to page number in pdf added
  app/lib/screens/landing_screen/dashboard.dart
  app/lib/screens/landing_screen/popupdetail.dart
  app/lib/screens/note_preview/preview_note_screen.dart
Labels: good first issue, gssoc, Level 2

#46 Fixed Paths to both CONTRIBUTING.md and CODE_OF_CONDUCT.md in readme.md
  readme.md
Labels: gssoc, Level 1

#48 Completed Share Feature For notes
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  app/.flutter-plugins-dependencies
  app/lib/screens/landing_screen/dashboard.dart
  app/pubspec.yaml
Labels: gssoc, Level 2

#69 remove duplicate auth screen
  .idea/libraries/Dart_SDK.xml
  app/.flutter-plugins-dependencies
  app/lib/screens/auth_screen/auth_screen/signin.dart
  app/lib/screens/auth_screen/auth_screen/signup.dart
Labels: gssoc, Level 1

#71 made the UI of otp page
  app/lib/main.dart
  app/lib/screens/auth_screen/signup.dart
  app/lib/screens/landing_screen/dashboard.dart
Labels: gssoc, Level 3

#81 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: gssoc, Level 1

#59 dashboard ui change
  app/.flutter-plugins-dependencies
  app/assets/img/civil.png
  app/assets/img/cse.png
  app/assets/img/diploma.png
  app/assets/img/doctor.png
  app/assets/img/ece.png
  app/assets/img/ee.png
  app/assets/img/eng.png
  app/assets/img/nurs.png
  app/assets/img/phar.png
  app/lib/main.dart
  app/lib/screens/auth_screen/otp.dart
  app/lib/screens/auth_screen/signup.dart
  app/lib/screens/courses/btech_course.dart
  app/lib/screens/landing_screen/dashboard.dart
  app/lib/services/ApiServices/ApiBaseServices.dart
  app/lib/services/ApiServices/api_services.dart.dart
Labels: gssoc, Level 3

#84 Discussion Page
  app/.flutter-plugins-dependencies
  app/lib/main.dart
  app/lib/screens/discussion/comments.dart
  app/lib/screens/discussion/discussion.dart
  app/lib/screens/landing_screen/drawer.dart
Labels: gssoc, Level 2

#80 Addde password and email validator and Fixed Share and Like Bugs
  .idea/sonarlint/issuestore/e/2/e252570a660ebc14361175b3d8ac8ed083bbe453
  .idea/sonarlint/issuestore/e/2/e26f5a170f5adb60f1c596df95c210211bee01d0
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/0/d/0dbf64ab67d5b77e07878b7c6536877524fb3bab
  .idea/sonarlint/securityhotspotstore/5/d/5d839bd2da7da37e596569c1e30d5a97356bace9
  .idea/sonarlint/securityhotspotstore/6/9/69bfb62dab887d57d64102dd308b3322a739fbb9
  .idea/sonarlint/securityhotspotstore/8/4/849fc186c9255796ca3143ae3405113c387d0000
  .idea/sonarlint/securityhotspotstore/8/a/8a0feae5bd6ac4c22753d3ad7af305a40c0e3be5
  .idea/sonarlint/securityhotspotstore/9/9/99e14883a0b77ddb8107df3445f7313d9bd84cf3
  .idea/sonarlint/securityhotspotstore/b/1/b11513a97a44b96932c8b945b548e1771e8b6e1e
  .idea/sonarlint/securityhotspotstore/b/8/b8cfd1c65c8239ee02215e7fdcc52233fd3a5cd6
  .idea/sonarlint/securityhotspotstore/c/2/c268c108bee4d54fa6fc2f81d69bf39cff6491ce
  .idea/sonarlint/securityhotspotstore/f/9/f9ecd45652880c432ef9bc3717411ba1bbcad91f
  .idea/sonarlint/securityhotspotstore/index.pb
  app/.flutter-plugins-dependencies
  app/android/build.gradle
  app/lib/main.dart
  app/lib/model/notes.dart
  app/lib/screens/auth_screen/signin.dart
  app/lib/screens/auth_screen/signup.dart
  app/lib/screens/landing_screen/dashboard.dart
  app/lib/screens/liked_notes/liked.dart
  app/lib/screens/note_preview/preview_note_screen.dart
  app/lib/services/SharedServices/Sharedservices.dart
Labels: gssoc, Level 2, under review

#63 Added login authentication and validated empty field with alert option
  app/lib/screens/auth_screen/signin.dart
  app/lib/screens/auth_screen/signup.dart
Labels: gssoc, Level 2

#92 @Subhash23jan fixed share and like feature
  .gitignore
  .idea/ExamTime_android.iml
  .idea/libraries/Dart_Packages.xml
  .idea/libraries/Dart_SDK.xml
  app/.flutter-plugins-dependencies
  app/lib/main.dart
  app/lib/screens/auth_screen/otp.dart
  app/lib/screens/auth_screen/signin.dart
  app/lib/screens/auth_screen/signup.dart
  app/lib/screens/landing_screen/dashboard.dart
  app/lib/services/ApiServices/ApiBaseServices.dart
  app/lib/services/ApiServices/api_services.dart.dart
  app/lib/services/SharedServices/Sharedservices.dart
Labels: gssoc, Level 3

#104 removed bug from otp page
  .idea/sonarlint/issuestore/4/b/4bbb62a3f15715a20cd38ef059d61f709918d394
  .idea/sonarlint/issuestore/index.pb
  .idea/sonarlint/securityhotspotstore/4/b/4bbb62a3f15715a20cd38ef059d61f709918d394
  .idea/sonarlint/securityhotspotstore/index.pb
  app/.flutter-plugins-dependencies
  app/lib/screens/auth_screen/signup.dart
  app/lib/services/ApiServices/ApiBaseServices.dart
  app/lib/services/ApiServices/api_services.dart.dart
Labels: gssoc, level2
